modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="l2library"
version="${file.jarVersion}" #mandatory
displayName="LightLand Library" #mandatory
logoFile="l2library.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2library]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2library]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"